### ISSUE TITLE
#119 – Category Screen  

### ISSUE THREAD

**Issue by JINGYANLOLA** [cs394-w19/crush-it#8]
As a user, I want to view a Category Screen/Homepage after completing a quiz so that I can determine where I’d like to go next in the app.  From this page, I could view my quiz history and choose another quiz to take. 

- [x] #119a Learner can view circles for three levels within a category. 
- [x] #119b Learner can tap a level to take or retake that level. 
- [ ] #119c Learner can see their most recent score on a level, until they get a perfect score on that level, and then the perfect score remains even if they retake it.

**Comment by zuzivian** [comment]
- require assets for uncompleted rings
- require persistence/authentication
